trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    sudo npm install -g aws-cdk
    cd fargate-service-with-auto-scaling
    npm install
    npm run build
    cdk synth
  displayName: 'npm install and build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/fargate-service-with-auto-scaling/cdk.out'
    ArtifactName: 'CDKOut'
    publishLocation: 'Container'